### ISSUE TITLE
Redesign functions

### ISSUE THREAD

**Issue by emitanaka** [EdgarSantos-Fernandez/SSNbayes#2]
E.g. `pred_ssnbayes()` could be come like `predict.ssnbayes()` (requires you to create an object with class `ssnbayes` if so). This leverages commonly used S3 method for models that many R users would be familiar with.

Further extensions are consider creating methods that are aligned with the `broom` package (i.e. `tidy`, `augment`, `glance`) and its output format.

**Comment by EdgarSantos-Fernandez** [comment]
Thank you @emitanaka , this was a great recommendation :) Already incorporated in the new version.
